# This has codecov report everything to us, but makes it not required to pass
# for PRs to be merged.
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
