# This has codecov report everything to us, but makes it not required to pass
# for PRs to be merged.
coverage:
  status:
    project:
      default:
        # PRs should not reduce coverage
        target: auto
    patch:
      default:
        # All new code should have test coverage.
        target: 100%
